language: node_js

sudo: false

env:
  - secure: "r5XBagbiwNvW5ah+IlErvwJh6r13kVnjIA3MJclmVyUMi66439RcyfYYWWZuYylkFO7cKE/x+1CYcnWvbtx3LM+02c9jGzAr1sZ2nOrnBusytNXcBz7LDi+MVB5ZTbsM4+ZITDXLNXpE893yjBju8pUmKQxFv2QhDFJl1jVSNHDuZxcExbtGtXCqgbRPkr0zG5/d6dinehXMrDrTsp585LdL+QPPM9i4nxgvP6TP/jcjIi8mNr2qB+jWiG8G0Bncb62xllZVkHFeGkgDF5J1/9uvG/KKqj2ikbfvZvRJz9SrRNRXt5WNhweVpFconKzzeQi+qcrDDUJGhZ+yog7NWDUs9n6BLaLPedQu3Rwl8FzEHLp4xfX1N+JwVsSLOPbbUokrcnaBRJy2rpXGwERn7EuDqN6ClCJsgAZ7ARTIwEvirismI0+bV1rHMWD29ChZf7mUiDn6VLQf2T90AzNQfgvqwemHs+lJbAZsm1OL4KZ7gal65oCmT/NZmrPO+Rdb7Umnwc6kPSWFloKcYgTjrw44wAskcbjS7y2XjoK2C61yI3e8RuZekFurLmnjBxyz+IRYXJUyv+tQrVoJySxK0u+XJUAT+yvqWCHdkc9riKOXH3+AAsLZNJrOaD+gv3Sefm/tzKtSVYCQ8I8oPF0a9lwh6eXyTYViGv8WtzU+Xlg="

node_js:
  - '0.10'

install:
  - npm install

script:
  - grunt test --all

after_success:
  - grunt codeclimate
