language: node_js

sudo: false

env:
  - secure: "ObnuXzaPi8q9HG7ZJvnCjMjhemDHGoZxlwRs0hluWou6iJR7vuFxcjtjDPJpafxhGegvPSoTDhKlZTF6uCjIhxlD8Gh7qocCfF38M+m7qSEopWTyTqIHbI5ugtSDS87A2plL0rqWbJezO8AkgOU8Plb3TmDW5Jxloqyc7pLiZ4spevIT1f64T9iY4ukheMuB16+2AXSIbSlJTbyr48cJTigV0HGpu6AhckrIw2Of81ndVep/mep4hGUpehn8G1YDXdeWSsD5xQMc6GjDHwSHCwE2M+OhurREBMksol+w38timZsOq6vue1c/EmF0NVtrz6hyKjfxVCqJGJxOQ0PIvzEdykDSHYGANh/0yqaT3rVlqG5kmxLYr74o+K+7X86OdW/kZV3iAFMbYM977q6dfFrYuUWUxdgoeAOd1TrM0NpLRkc3Hs9E00gnzCLSVMjkkH29NJ6qjFCYmAvE0In46J31hEyFkniTt0gh+3i7JMvfAnziY9DNBgyxK12TaqKk3wdjuJvmQtZA+MILn++ATsUcgot5ajjLbAw7ja+94UZ8uOLbLzjlC98ZzjmiHO/QitGtxt3hQFJEmrWK79KebKHj4QyKsqVDFFN8gLSsqAbw6WMvqW8rLQGwGeyEAA06o4CEOtQO8dQpFy2qZu+ZHTr5uc+v7o6TrdqlD8ndDsc="

node_js:
  - '0.10'

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - grunt test --all
  - grunt shell:testSampleProject

after_success:
  - grunt codeclimate
