language: node_js

sudo: false

env:
  - secure: "oCBaJ7L/iUH8KDJsGPRvO0ZaJC6etmQzT6Bc7dEkxeZWlC90uxn5B/Lb0E+6QGEqzzBYMzasG9eymUDI2UL1XEYDVYsZvEbEveYNQj8uQrZ9vOVDXuhF/S5an03jEsq5tANkuxZJU57IJrtBpWL1FcZU5HtwW/F5bxcr8PvSv1Ku/Ty8ZfBgX23bt3jBEiUJZJaHM9DmW6Jp9UfAzXmmVqLGRfleuVeVa5y5atAip6lWJ5eHVt/Z5BccH3fTmequmQZwkPW99TMziAKYHqylbrT/U0nwGt6o6rHrYfM1km7xCyB48QKzTCISI8SxmWEXYoHjjiWb+twaVS9u2QmWVPpfD+U4rv5LxUO5E8jBle4+7WmM4USre7CsRX59CrmX5uwaoQnid1cF52UDoVBP6zEhz/Fi1tp5pLkvOl0QTRA7l8KnZhnVb0DOhyaWA3eiJtJ2QPUjqg1cQyslzHPeNuTEmY3i0uIMA2ulc1BveLteO1GM+rpDQZXSPlutCRrunMp6aHJSRcKwa0E98Dap+4KcG/ZgfCspmsK9vePcS1JKs/YM9kIE+99Yph01FvVyMBHhsRXtQm5RhG7aBqGY8Jj5YfwzqtAAYK9dcGNQJOK7aB0b3W7WOjkjFfHbigGrf2eJNLDUhcGdYVbJMzJ75S+vWTqfx50rOKayn2QicQg="

node_js:
  - '0.10'

install:
  - npm install

script:
  - grunt test --all

after_success:
  - grunt codeclimate
